services:
  mysql:
    image: mysql:8.0
    container_name: log-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: appotintment
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - log_mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  log-storage:
    build: ./database
    container_name: appointment-storage
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - ./database/.env
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=appotintment
      - DB_PORT=3306
    command: npm start

  log_phpmyadmin:
    image: phpmyadmin:latest
    container_name: appointment-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=appointment-mysql
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

volumes:
  appointment_mysql_data: